[package]
edition      = "2021"
name         = "gps"
rust-version = "1.86"
version      = "0.1.0"

[[bin]]
name = "gps"
path = "./src/bin/main.rs"

[dependencies]
defmt = "1.0.1"
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32c3"] }
esp-hal = { version = "=1.0.0-rc.0", features = [
  "defmt",
  "esp32c3",
  "unstable",
] }
nb = "1.1.0"
critical-section = "1.2.0"
esp-println      = { version = "0.15.0", features = ["defmt-espflash", "esp32c3"] }
esp-alloc = { version = "0.8.0", features = ["defmt"] }
heapless = { version = "0.8.0", default-features = false }
libm = "0.2.8"

geohash = { path = "../geohash", default-features = false }
phf = { version = "0.11", default-features = false }

# Embassy dependencies
embassy-executor = { version = "0.7.0", features = [
  "defmt",
  "task-arena-size-65536",
] }
embassy-time     = { version = "0.5.0", features = ["defmt"] }
embassy-sync     = { version = "0.6.1", features = ["defmt"] }
esp-hal-embassy  = { version = "0.9.0", features = ["defmt", "esp32c3"] }
static_cell      = "2.1.1"

# LED dependencies
esp-hal-smartled = { git = "https://github.com/esp-rs/esp-hal-community", package = "esp-hal-smartled", features = ["esp32c3"] }
smart-leds = "=0.4.0"

# WiFi and Networking dependencies
embassy-net = { version = "0.7.0", features = [
  "defmt",
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embedded-io = { version = "0.6.1", features = ["defmt-03"] }
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }
esp-wifi = { version = "0.15.0", features = [
  "builtin-scheduler",
  "defmt",
  "esp-alloc",
  "esp32c3",
  "smoltcp",
  "wifi",
] }
smoltcp = { version = "0.12.0", default-features = false, features = [
  "defmt",
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }
picoserve = { version = "0.15.0", features = ["embassy"] }
anyhow = { version = "1.0.95", default-features = false }
esp-hal-dhcp-server = "0.2.7"
esp-hal-ota = { version = "0.4.5" }
esp-storage = { version = "0.7.0", features = ["esp32c3"] }
serde = { version = "1.0.217", default-features = false, features = ["derive"] }

[build-dependencies]
phf_codegen = "0.11"
phf = { version = "0.11", default-features = false }
